-- Panel editable del filtro de envío (Filtros del cotizador v10 — ver
-- src/lib/sobrecargoEnvio.ts). Hasta ahora las 5 listas de términos de
-- alarma (~250 términos EN/ES/JP) y los 6 umbrales numéricos vivían
-- hardcodeados en código: cada ajuste requería un deploy. Estas dos
-- tablas los mueven a Supabase para que /admin/filtro-envio pueda
-- editarlos en caliente. El código sigue trayendo las mismas constantes
-- como default/fallback fail-open (ver CONFIG_DEFAULT/LISTAS_DEFAULT en
-- sobrecargoEnvio.ts) — un problema de Supabase nunca rompe una
-- cotización, solo deja de reflejar ediciones recientes del panel.
--
-- Mismo patrón RLS que `settings`: lectura pública (el cotizador y el
-- carrito del cliente la necesitan), escritura solo vía service-role
-- (la API valida admin con esEmailAdmin() antes de escribir).

create table if not exists filtro_envio_terminos (
  id uuid primary key default gen_random_uuid(),
  categoria text not null check (categoria in
    ('voluminosas', 'pesadas', 'precision', 'exclusiones', 'subpiezas')),
  termino text not null,
  created_at timestamptz not null default now(),
  unique (categoria, termino)
);

alter table filtro_envio_terminos enable row level security;

drop policy if exists filtro_envio_terminos_public_read on filtro_envio_terminos;
create policy filtro_envio_terminos_public_read on filtro_envio_terminos
  for select to anon, authenticated using (true);

create table if not exists filtro_envio_config (
  id smallint primary key default 1 check (id = 1),
  peso_incluido_kg numeric not null default 0.5,
  cobro_kilo_extra_clp numeric not null default 22000,
  peso_maximo_kg numeric not null default 4,
  precio_seguro_sin_peso_clp numeric not null default 30000,
  exencion_voluminosas_kg numeric not null default 0.5,
  precio_minimo_voluminosa_clp numeric not null default 10000,
  updated_at timestamptz not null default now()
);

alter table filtro_envio_config enable row level security;

insert into filtro_envio_config (id) values (1) on conflict (id) do nothing;

drop policy if exists filtro_envio_config_public_read on filtro_envio_config;
create policy filtro_envio_config_public_read on filtro_envio_config
  for select to anon, authenticated using (true);

-- Semilla: los ~250 términos actuales de VOLUMINOSAS/PESADAS/PRECISION/
-- EXCLUSIONES/SUBPIEZAS en sobrecargoEnvio.ts, generados
-- programáticamente desde el archivo real (no transcritos a mano) para
-- que la tabla arranque con cobertura idéntica a la que había en
-- código. No hay columna de idioma: el matching autodetecta japonés vía
-- RE_JAPONES en contieneTermino(), da igual si el término es "COWL",
-- "CARENADO" o "カウル".
insert into filtro_envio_terminos (categoria, termino) values
  ('voluminosas', 'COWL'),
  ('voluminosas', 'COWLING'),
  ('voluminosas', 'FAIRING'),
  ('voluminosas', 'FENDER'),
  ('voluminosas', 'TANK'),
  ('voluminosas', 'HEADLIGHT'),
  ('voluminosas', 'HEADLAMP'),
  ('voluminosas', 'HEAD LAMP'),
  ('voluminosas', 'MUFFLER'),
  ('voluminosas', 'EXHAUST PIPE'),
  ('voluminosas', 'RADIATOR'),
  ('voluminosas', 'SWINGARM'),
  ('voluminosas', 'SWINGING ARM'),
  ('voluminosas', 'REAR ARM'),
  ('voluminosas', 'WHEEL'),
  ('voluminosas', 'TIRE'),
  ('voluminosas', 'FRAME'),
  ('voluminosas', 'SHELTER'),
  ('voluminosas', 'SEAT ASSY'),
  ('voluminosas', 'SEAT COMP'),
  ('voluminosas', 'FORK ASSY'),
  ('voluminosas', 'HANDLEBAR'),
  ('voluminosas', 'HANDLE BAR'),
  ('voluminosas', 'FAT BAR'),
  ('voluminosas', 'SCREEN'),
  ('voluminosas', 'WINDSCREEN'),
  ('voluminosas', 'DUCT'),
  ('voluminosas', 'SHROUD'),
  ('voluminosas', 'SIDE COVER'),
  ('voluminosas', 'CARROCERIA'),
  ('voluminosas', 'CARENADO'),
  ('voluminosas', 'GUARDABARROS'),
  ('voluminosas', 'TANQUE'),
  ('voluminosas', 'DEPOSITO COMBUSTIBLE'),
  ('voluminosas', 'FARO'),
  ('voluminosas', 'SILENCIADOR'),
  ('voluminosas', 'TUBO ESCAPE'),
  ('voluminosas', 'RADIADOR'),
  ('voluminosas', 'BASCULANTE'),
  ('voluminosas', 'HORQUILLA TRASERA'),
  ('voluminosas', 'RUEDA'),
  ('voluminosas', 'NEUMATICO'),
  ('voluminosas', 'CHASIS'),
  ('voluminosas', 'MANILLAR'),
  ('voluminosas', 'PARABRISAS'),
  ('voluminosas', 'カウル'),
  ('voluminosas', 'フェアリング'),
  ('voluminosas', 'フェンダ'),
  ('voluminosas', 'タンク'),
  ('voluminosas', 'ヘッドライト'),
  ('voluminosas', 'ヘッドランプ'),
  ('voluminosas', 'マフラ'),
  ('voluminosas', 'エキゾースト'),
  ('voluminosas', 'エキパイ'),
  ('voluminosas', 'ラジエータ'),
  ('voluminosas', 'スイングアーム'),
  ('voluminosas', 'リヤアーム'),
  ('voluminosas', 'ホイール'),
  ('voluminosas', 'タイヤ'),
  ('voluminosas', 'フレーム'),
  ('voluminosas', 'シェルタ'),
  ('voluminosas', 'シートアッシ'),
  ('voluminosas', 'シートコンプ'),
  ('voluminosas', 'フロントフォーク'),
  ('voluminosas', 'ハンドルバー'),
  ('voluminosas', 'スクリーン'),
  ('voluminosas', 'ダクト'),
  ('voluminosas', 'シュラウド'),
  ('voluminosas', 'サイドカバー'),
  ('pesadas', 'CRANKSHAFT'),
  ('pesadas', 'CYLINDER HEAD'),
  ('pesadas', 'CRANKCASE'),
  ('pesadas', 'CYLINDER'),
  ('pesadas', 'FLYWHEEL'),
  ('pesadas', 'STARTER MOTOR'),
  ('pesadas', 'STARTING MOTOR'),
  ('pesadas', 'ALTERNATOR'),
  ('pesadas', 'GENERATOR'),
  ('pesadas', 'STATOR'),
  ('pesadas', 'CAMSHAFT'),
  ('pesadas', 'TRANSMISSION'),
  ('pesadas', 'GEARBOX'),
  ('pesadas', 'SHOCK ABSORBER'),
  ('pesadas', 'TRIPLE CLAMP'),
  ('pesadas', 'STEERING STEM'),
  ('pesadas', 'BRAKE DISC'),
  ('pesadas', 'DISC ROTOR'),
  ('pesadas', 'CALIPER'),
  ('pesadas', 'DRIVE CHAIN'),
  ('pesadas', 'SPROCKET'),
  ('pesadas', 'BATTERY'),
  ('pesadas', 'SIDE STAND'),
  ('pesadas', 'CENTER STAND'),
  ('pesadas', 'PROP STAND'),
  ('pesadas', 'AIR CLEANER ASSY'),
  ('pesadas', 'CIGUENAL'),
  ('pesadas', 'CABEZA CILINDRO'),
  ('pesadas', 'CARTER'),
  ('pesadas', 'VOLANTE MOTOR'),
  ('pesadas', 'MOTOR ARRANQUE'),
  ('pesadas', 'ALTERNADOR'),
  ('pesadas', 'GENERADOR'),
  ('pesadas', 'ESTATOR'),
  ('pesadas', 'ARBOL LEVAS'),
  ('pesadas', 'TRANSMISION'),
  ('pesadas', 'CAJA CAMBIOS'),
  ('pesadas', 'MORDAZA'),
  ('pesadas', 'CADENA TRANSMISION'),
  ('pesadas', 'PINON'),
  ('pesadas', 'BATERIA'),
  ('pesadas', 'CABALLETE LATERAL'),
  ('pesadas', 'CABALLETE CENTRAL'),
  ('pesadas', 'LIMPIADOR AIRE'),
  ('pesadas', 'クランクシャフト'),
  ('pesadas', 'シリンダ'),
  ('pesadas', 'クランクケース'),
  ('pesadas', 'フライホイール'),
  ('pesadas', 'セルモータ'),
  ('pesadas', 'スターターモータ'),
  ('pesadas', 'スタータ'),
  ('pesadas', 'オルタネータ'),
  ('pesadas', 'ジェネレータ'),
  ('pesadas', 'ステータ'),
  ('pesadas', 'カムシャフト'),
  ('pesadas', 'ミッション'),
  ('pesadas', 'ギヤボックス'),
  ('pesadas', 'ギアボックス'),
  ('pesadas', 'ショックアブソーバ'),
  ('pesadas', 'トップブリッジ'),
  ('pesadas', 'ステアリングステム'),
  ('pesadas', 'ブレーキディスク'),
  ('pesadas', 'ディスクロータ'),
  ('pesadas', 'キャリパ'),
  ('pesadas', 'ドライブチェーン'),
  ('pesadas', 'スプロケット'),
  ('pesadas', 'バッテリ'),
  ('pesadas', 'サイドスタンド'),
  ('pesadas', 'センタースタンド'),
  ('pesadas', 'エアクリーナ'),
  ('precision', 'INJECTOR'),
  ('precision', 'IGNITER'),
  ('precision', 'IGNITION COIL'),
  ('precision', 'CDI'),
  ('precision', 'ECU'),
  ('precision', 'ECM'),
  ('precision', 'RELAY'),
  ('precision', 'REGULATOR'),
  ('precision', 'RECTIFIER'),
  ('precision', 'SOLENOID'),
  ('precision', 'SPARK PLUG'),
  ('precision', 'FUSE'),
  ('precision', 'MODULE'),
  ('precision', 'SWITCH'),
  ('precision', 'CONTROL UNIT'),
  ('precision', 'SENSOR'),
  ('precision', 'INYECTOR'),
  ('precision', 'BUJIA ENCENDIDO'),
  ('precision', 'RELE'),
  ('precision', 'REGULADOR'),
  ('precision', 'RECTIFICADOR'),
  ('precision', 'SOLENOIDE'),
  ('precision', 'BUJIA'),
  ('precision', 'FUSIBLE'),
  ('precision', 'UNIDAD CONTROL'),
  ('precision', 'インジェクタ'),
  ('precision', 'イグナイタ'),
  ('precision', 'イグニッションコイル'),
  ('precision', 'リレー'),
  ('precision', 'レギュレータ'),
  ('precision', 'レクチファイヤ'),
  ('precision', 'ソレノイド'),
  ('precision', 'スパークプラグ'),
  ('precision', 'プラグ'),
  ('precision', 'ヒューズ'),
  ('precision', 'スイッチ'),
  ('precision', 'センサ'),
  ('precision', 'コントロールユニット'),
  ('exclusiones', 'MASTER CYLINDER'),
  ('exclusiones', 'KEY CYLINDER'),
  ('exclusiones', 'CYLINDER LOCK'),
  ('exclusiones', 'CYLINDER STUD'),
  ('exclusiones', 'CYLINDER BOLT'),
  ('exclusiones', 'CYLINDER GASKET'),
  ('exclusiones', 'CYLINDER HEAD GASKET'),
  ('exclusiones', 'CYLINDER HEAD BOLT'),
  ('exclusiones', 'CYLINDER HEAD COVER'),
  ('exclusiones', 'CRANKCASE GASKET'),
  ('exclusiones', 'CRANKCASE BOLT'),
  ('exclusiones', 'TANK CAP'),
  ('exclusiones', 'TANK BADGE'),
  ('exclusiones', 'TANK EMBLEM'),
  ('exclusiones', 'TANK RUBBER'),
  ('exclusiones', 'TANK PAD'),
  ('exclusiones', 'RESERVE TANK'),
  ('exclusiones', 'RESERVOIR TANK'),
  ('exclusiones', 'RECOVERY TANK'),
  ('exclusiones', 'WHEEL BEARING'),
  ('exclusiones', 'WHEEL VALVE'),
  ('exclusiones', 'WHEEL BOLT'),
  ('exclusiones', 'WHEEL NUT'),
  ('exclusiones', 'SPROCKET BOLT'),
  ('exclusiones', 'SPROCKET NUT'),
  ('exclusiones', 'SPROCKET COVER'),
  ('exclusiones', 'CAM SPROCKET'),
  ('exclusiones', 'HUB SHOCK'),
  ('exclusiones', 'HANDLEBAR BALANCER'),
  ('exclusiones', 'CALIPER BOLT'),
  ('exclusiones', 'CALIPER SEAL'),
  ('exclusiones', 'CALIPER PISTON'),
  ('exclusiones', 'BATTERY CABLE'),
  ('exclusiones', 'BATTERY HOLDER'),
  ('exclusiones', 'BATTERY BAND'),
  ('exclusiones', 'RADIATOR CAP'),
  ('exclusiones', 'RADIATOR HOSE'),
  ('exclusiones', 'RADIATOR BOLT'),
  ('exclusiones', 'STATOR BOLT'),
  ('exclusiones', 'STATOR COVER GASKET'),
  ('exclusiones', 'CAMSHAFT SPROCKET'),
  ('exclusiones', 'CAMSHAFT CHAIN'),
  ('exclusiones', 'CILINDRO MAESTRO'),
  ('exclusiones', 'TAPA TANQUE'),
  ('exclusiones', 'TAPON TANQUE'),
  ('exclusiones', 'EMBLEMA TANQUE'),
  ('exclusiones', 'VALVULA RUEDA'),
  ('exclusiones', 'TUERCA RUEDA'),
  ('exclusiones', 'TAPA RADIADOR'),
  ('exclusiones', 'MANGUERA RADIADOR'),
  ('exclusiones', 'マスターシリンダ'),
  ('exclusiones', 'キーシリンダ'),
  ('exclusiones', 'シリンダヘッドカバー'),
  ('exclusiones', 'エミッション'),
  ('subpiezas', 'BOLT'),
  ('subpiezas', 'GASKET'),
  ('subpiezas', 'SCREW'),
  ('subpiezas', 'WASHER'),
  ('subpiezas', 'NUT'),
  ('subpiezas', 'CLIP'),
  ('subpiezas', 'SEAL'),
  ('subpiezas', 'BRACKET'),
  ('subpiezas', 'STUD'),
  ('subpiezas', 'PIN'),
  ('subpiezas', 'HOSE'),
  ('subpiezas', 'CAP'),
  ('subpiezas', 'RUBBER'),
  ('subpiezas', 'SPRING'),
  ('subpiezas', 'COLLAR'),
  ('subpiezas', 'GROMMET'),
  ('subpiezas', 'BUSHING'),
  ('subpiezas', 'SLEEVE'),
  ('subpiezas', 'MARK'),
  ('subpiezas', 'DAMPER'),
  ('subpiezas', 'SPACER'),
  ('subpiezas', 'BEARING'),
  ('subpiezas', 'CABLE'),
  ('subpiezas', 'WIRE'),
  ('subpiezas', 'LEVER'),
  ('subpiezas', 'HOLDER'),
  ('subpiezas', 'ELEMENT'),
  ('subpiezas', 'LABEL'),
  ('subpiezas', 'BAND'),
  ('subpiezas', 'SHIM'),
  ('subpiezas', 'CORD'),
  ('subpiezas', 'EMBLEM'),
  ('subpiezas', 'BADGE'),
  ('subpiezas', 'TAPE'),
  ('subpiezas', 'LENS'),
  ('subpiezas', 'MOLDING'),
  ('subpiezas', 'PROTECTOR'),
  ('subpiezas', 'FASTENER'),
  ('subpiezas', 'CUSHION'),
  ('subpiezas', 'GRIP'),
  ('subpiezas', 'MIRROR'),
  ('subpiezas', 'REFLECTOR'),
  ('subpiezas', 'SOCKET'),
  ('subpiezas', 'BULB'),
  ('subpiezas', 'TORNILLO'),
  ('subpiezas', 'JUNTA'),
  ('subpiezas', 'EMPAQUETADURA'),
  ('subpiezas', 'TUERCA'),
  ('subpiezas', 'ARANDELA'),
  ('subpiezas', 'SELLO'),
  ('subpiezas', 'PERNO'),
  ('subpiezas', 'MANGUERA'),
  ('subpiezas', 'TAPA'),
  ('subpiezas', 'GOMA'),
  ('subpiezas', 'CAUCHO'),
  ('subpiezas', 'RESORTE'),
  ('subpiezas', 'MUELLE'),
  ('subpiezas', 'COLLARIN'),
  ('subpiezas', 'FUNDA'),
  ('subpiezas', 'CASQUILLO'),
  ('subpiezas', 'ESPACIADOR'),
  ('subpiezas', 'RODAMIENTO'),
  ('subpiezas', 'COJINETE'),
  ('subpiezas', 'PALANCA'),
  ('subpiezas', 'ETIQUETA'),
  ('subpiezas', 'CINTA'),
  ('subpiezas', 'EMBLEMA'),
  ('subpiezas', 'PROTECTOR'),
  ('subpiezas', 'SUJETADOR'),
  ('subpiezas', 'COJIN'),
  ('subpiezas', 'EMPUÑADURA'),
  ('subpiezas', 'PUÑO'),
  ('subpiezas', 'ESPEJO RETROVISOR'),
  ('subpiezas', 'REFLECTOR'),
  ('subpiezas', 'ENCHUFE'),
  ('subpiezas', 'BOMBILLA'),
  ('subpiezas', 'FOCO'),
  ('subpiezas', 'ボルト'),
  ('subpiezas', 'ガスケット'),
  ('subpiezas', 'パッキン'),
  ('subpiezas', 'スクリュ'),
  ('subpiezas', 'ビス'),
  ('subpiezas', 'ネジ'),
  ('subpiezas', 'ワッシャ'),
  ('subpiezas', 'ナット'),
  ('subpiezas', 'クリップ'),
  ('subpiezas', 'シール'),
  ('subpiezas', 'ブラケット'),
  ('subpiezas', 'スタッド'),
  ('subpiezas', 'ピン'),
  ('subpiezas', 'ホース'),
  ('subpiezas', 'キャップ'),
  ('subpiezas', 'ラバー'),
  ('subpiezas', 'スプリング'),
  ('subpiezas', 'カラー'),
  ('subpiezas', 'グロメット'),
  ('subpiezas', 'ブッシュ'),
  ('subpiezas', 'スリーブ'),
  ('subpiezas', 'ダンパ'),
  ('subpiezas', 'スペーサ'),
  ('subpiezas', 'ベアリング'),
  ('subpiezas', 'オーリング'),
  ('subpiezas', 'ケーブル'),
  ('subpiezas', 'ワイヤ'),
  ('subpiezas', 'レバー'),
  ('subpiezas', 'ホルダ'),
  ('subpiezas', 'エレメント'),
  ('subpiezas', 'ラベル'),
  ('subpiezas', 'バンド'),
  ('subpiezas', 'シム'),
  ('subpiezas', 'コード'),
  ('subpiezas', 'エンブレム'),
  ('subpiezas', 'テープ'),
  ('subpiezas', 'レンズ'),
  ('subpiezas', 'モール'),
  ('subpiezas', 'プロテクタ'),
  ('subpiezas', 'クッション'),
  ('subpiezas', 'グリップ'),
  ('subpiezas', 'ミラー'),
  ('subpiezas', 'リフレクタ'),
  ('subpiezas', 'ソケット')
on conflict (categoria, termino) do nothing;
